name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Gunakan v4 yang terbaru

      # ... step build kamu yang lain ...

      - name: Open Remote Terminal
        run: curl -sSf https://sshx.io/get | sh -s run
